### ISSUE TITLE
Service Status is Unavailable.

### ISSUE THREAD

**Issue by Shiza-Hasan** [crits/crits_services#183]
I configure the CRITs, using setconfig, to import the services, but on GUI all services status is 'Unavailable'. Am I missing something?
Help will be highly appreciated.

**Comment by webstergd** [comment]
What variable did you put for the service folder? Also what are the folders permissions?

**Comment by Shiza-Hasan** [comment]
I used following command for this purpose:
python manage.py setconfig service_dirs "/Downloads/crits_services"
And I have ownership of services folders.

**Comment by webstergd** [comment]
hum...follow on questions.
1) would you mind going into the director and executing pwd
2) would you mind going into /Downloads and executing ls -al
3) where do you have crits core located?

**Comment by Shiza-Hasan** [comment]
1) /home/aserg/Downloads/crits_services-master
2) "drwx -- -- --" against crits_services folder
3) crits core is located on Downloads/crits/crits-master

**Comment by webstergd** [comment]
your service directory you entered is incorrect. You need to enter the full
path which in your case is '/home/aserg/Downloads/crits_services-master'.

also if you are expecting multiple people to leverage your crits install, I
would personally recommend installing crits and crits services in
a separate root directory such as '/data'.
https://github.com/crits/crits/wiki/Production-grade-CRITs-install provides
a decent guide on how to set that up.

**Comment by Shiza-Hasan** [comment]
What will be the Crits email and Instamce url? is crits email is the email of user I created?
Thank you for you help :)

**Comment by Shiza-Hasan** [comment]
I used full path and also try by installing crits in '/data' directory but still having all services status 'unavailable'.

**Comment by Shiza-Hasan** [comment]
Error solved. Having some error in taxiiservice 'handle.py' file.

**Comment by webstergd** [comment]
so services being unavailable is almost always because either the path you
are supplying is incorrect or you have a permissions issue. Thus, make sure
your path is correct and that the crits core has the permissions needed to
access the service folder.

If you are still having trouble you can send the crits.log and/or apache
error log and I can see if i can figure out what it happening.

As for your previous 2 questions:
1) CRITs Email is the email of the administrator. It does not have to be
related to any crits user. Just an address for the administrator.
2) the instance url is the url for your hosted version of crits. So if you
are using http://crits.shizahasan.com/, then that is your instance url

**Comment by webstergd** [comment]
Awesome! glad to hear you figured it out. What ended up being the problem?
